In [1]:
import torch

In [15]:
a = torch.tensor([
    [1,1,1,3,4,6],
    [2,2,2,6,3,6],
    [3,3,3,7,9,0]
], dtype=torch.float32)

In [16]:
means = torch.mean(a, dim=1, keepdim=True)

In [21]:
x = a - means

In [22]:
std = torch.std(a, dim=1, keepdim=True)

In [23]:
std

tensor([[2.0656],
        [1.9748],
        [3.2506]])

In [24]:
x = x / std

In [25]:
x

tensor([[-0.8069, -0.8069, -0.8069,  0.1614,  0.6455,  1.6137],
        [-0.7596, -0.7596, -0.7596,  1.2659, -0.2532,  1.2659],
        [-0.3589, -0.3589, -0.3589,  0.8716,  1.4869, -1.2818]])

In [27]:
b = (a - a.mean()) / a.std()

In [28]:
b

tensor([[-1.0056, -1.0056, -1.0056, -0.1828,  0.2286,  1.0513],
        [-0.5942, -0.5942, -0.5942,  1.0513, -0.1828,  1.0513],
        [-0.1828, -0.1828, -0.1828,  1.4627,  2.2855, -1.4170]])