In [28]:
import torch

In [29]:
##create Batch, np of captions for image, and max length of caption
x = torch.rand(3, 5, 10)

In [30]:
x

tensor([[[1.8309e-01, 9.6665e-01, 2.1604e-01, 1.4143e-01, 2.2786e-01,
          5.9938e-01, 2.3588e-02, 8.6126e-01, 7.0469e-01, 6.6908e-01],
         [4.0389e-01, 6.3509e-01, 9.2100e-01, 9.8789e-01, 9.4341e-01,
          5.0234e-01, 6.7010e-01, 9.7614e-01, 3.5053e-01, 5.0826e-01],
         [3.4497e-01, 6.8619e-01, 1.3458e-01, 9.2432e-01, 6.6425e-01,
          6.4152e-01, 5.3626e-01, 7.9882e-01, 4.2679e-01, 3.7507e-01],
         [2.8204e-01, 5.6221e-01, 3.5856e-01, 3.8171e-01, 9.3186e-01,
          1.0485e-01, 6.6113e-01, 9.3369e-01, 8.8801e-01, 5.6209e-01],
         [4.3299e-01, 4.4264e-01, 5.8426e-02, 1.3672e-02, 4.0066e-01,
          8.2865e-01, 5.5597e-01, 1.5801e-01, 5.3755e-01, 6.7158e-03]],

        [[3.4626e-01, 6.5715e-01, 2.5919e-01, 4.3593e-01, 6.1675e-01,
          8.2351e-01, 9.8431e-01, 9.9162e-01, 6.7120e-01, 4.0493e-01],
         [3.8958e-01, 8.6369e-01, 1.1498e-01, 5.4591e-01, 2.1700e-01,
          2.3663e-02, 7.2431e-01, 9.2324e-01, 8.5344e-02, 5.8792e-01],
         [9

In [31]:
x = x.permute(0, 2, 1)

In [32]:
x.shape

torch.Size([3, 10, 5])

In [33]:
x = x[:, :, 1]

In [34]:
x.shape

torch.Size([3, 10])

In [35]:
x

tensor([[0.4039, 0.6351, 0.9210, 0.9879, 0.9434, 0.5023, 0.6701, 0.9761, 0.3505,
         0.5083],
        [0.3896, 0.8637, 0.1150, 0.5459, 0.2170, 0.0237, 0.7243, 0.9232, 0.0853,
         0.5879],
        [0.6850, 0.8799, 0.4510, 0.0311, 0.8807, 0.6096, 0.5659, 0.5012, 0.2072,
         0.9429]])

In [36]:
x[:, :-1]

tensor([[0.4039, 0.6351, 0.9210, 0.9879, 0.9434, 0.5023, 0.6701, 0.9761, 0.3505],
        [0.3896, 0.8637, 0.1150, 0.5459, 0.2170, 0.0237, 0.7243, 0.9232, 0.0853],
        [0.6850, 0.8799, 0.4510, 0.0311, 0.8807, 0.6096, 0.5659, 0.5012, 0.2072]])

In [37]:
y = torch.rand(3, 5, 10)

In [38]:
y

tensor([[[0.9138, 0.4375, 0.1113, 0.5708, 0.5732, 0.4338, 0.2433, 0.4372,
          0.3471, 0.3558],
         [0.3803, 0.2142, 0.2433, 0.8983, 0.2209, 0.3859, 0.1602, 0.6012,
          0.8418, 0.9650],
         [0.2599, 0.5580, 0.7951, 0.8678, 0.7041, 0.6026, 0.3966, 0.5266,
          0.2800, 0.8938],
         [0.2432, 0.0383, 0.7133, 0.2539, 0.1989, 0.0170, 0.3822, 0.4102,
          0.6808, 0.1765],
         [0.8208, 0.0471, 0.4564, 0.2578, 0.6362, 0.0042, 0.5706, 0.4151,
          0.8962, 0.9248]],

        [[0.6142, 0.6199, 0.7774, 0.6848, 0.5066, 0.1479, 0.6640, 0.2672,
          0.1775, 0.9524],
         [0.7511, 0.1061, 0.4983, 0.5853, 0.9392, 0.2288, 0.4791, 0.5381,
          0.6262, 0.5084],
         [0.4974, 0.0709, 0.8065, 0.8296, 0.8019, 0.4163, 0.7555, 0.7413,
          0.7415, 0.8246],
         [0.4418, 0.5640, 0.9127, 0.8121, 0.4097, 0.8894, 0.6719, 0.0024,
          0.5020, 0.8582],
         [0.9660, 0.7346, 0.4831, 0.2203, 0.6004, 0.8607, 0.9528, 0.1759,
          0.667

In [39]:
y = y[:, 1, :]

In [41]:
y.shape

torch.Size([3, 10])

In [42]:
y = y[:, :-1]